### PR TITLE
Make repos list use GitHub API

### PR DESCRIPTION
**Pull request by jessicard**
Make repos list use GitHub API.

Since it's a static site, we are using the unauthenticated API to grab open repos.

Fixes https://github.com/hackclub/contribute/issues/4 and https://github.com/hackclub/contribute/issues/6.

Screen Shot 2022-03-14 at 1 45 11 PM

### CODE REVIEW

**Review by exu3 — COMMENTED** [review]
image 
Cool stuff!

- It's sort of hard to tell what the number in the red badge means; maybe adding "issues" to it would help make it clearer?
- Instead of "Last pushed at [date/time]" maybe "Last updated [time difference] ago". Makes it a bit easier to read.
<details>
<summary>Idea: Thoughts on a grid layout? There seems to be a lot of empty space in the cards.</summary>
Screen Shot 2022-03-14 at 16 18 09

</details>

**Review by sampoder — CHANGES_REQUESTED** [review]
Plus one on Ella's comments, I think a grid would be best

**Comment by jessicard** [comment]
@exu3 @sampoder Yes on all of these! I'll get an update pushed up :)

**Comment by jessicard** [comment]
@exu3 @sampoder Done! I know the issues & prs language is lengthy. We are running into an issue where, underneath, GitHub considers PRs and issues the same, so the API returns `open_issues_count` with the PRs included. There's no PR count returned with this endpoint, and we'll need to authenticate if we are going to do anything fancier I think. Not opposed to making it a full JS app to authenticate for the API, but want to get this out for now so we can use it tomorrow.

Screen Shot 2022-03-16 at 11 11 03 AM

**Comment by jessicard** [comment]
@exu3 @sampoder Going to merge this for now so I can get going on getting this out, but feedback is welcome!!

**Comment by exu3** [comment]
> I know the issues & prs language is lengthy. We are running into an issue where, underneath, GitHub considers PRs and issues the same, so the API returns open_issues_count with the PRs included. 

Hmm maybe we could triage all the issues in active repos and tag them with "good-first-issue" as appropriate & have the badge show the number of issues with the "good-first-issue" label. 

> There's no PR count returned with this endpoint, and we'll need to authenticate if we are going to do anything fancier I think. Not opposed to making it a full JS app to authenticate for the API, but want to get this out for now so we can use it tomorrow.

I think it's important to keep this site static if it's going to serve as a demo use case of hackclub/css-theme. If necessary, maybe we could add an API route in hackclub/site to fetch data from GitHub and make a request to that endpoint instead of the GitHub API directly to get around rate limiting or if anything fancier is desired? Something like https://v3-1270gks8x.hackclub.dev/api/github/ (https://github.com/hackclub/site/commit/aa99f22181b5df7636b1eb2d1f1a3205d3fa14bc)

**Comment by jessicard** [comment]
@exu3 I totally agree about keeping it static if possible. If we need to make it an appy app, we could make a different demo, but for now I think keeping it static is ideal.

If we grabbed issues by their tag, since we're not using the GraphQL API (you need auth for it), it'll increase the queries from 1 query to N queries, since we'll have to query each repo. Right now we are querying 1 user (hack club). We are limited to 60 queries per hour while unauthenticated.

I love the idea of adding an API route in site! Then we aren't limited in what we want to do.

I also like the idea of tagging issues. I'm afraid this site will quickly become not useful if people aren't tagging issues though. So for now, maybe we just show all issues until we feel like everyone is tagging issues? I don't know, what do you think? 

One note on `good first issue` - I was initially using this tag, but GitHub aggregates them for users to easily find open source issues to work on. Which is great in theory, but I'd love to keep these issues around for Hack Clubbers specifically to work on. I've started using `beginner friendly` as a tag instead. What do you think?

**Comment by sampoder** [comment]
We can also add API routes in this repo coz it's deployed on Vercel :D

**Comment by jessicard** [comment]
@exu3 @sampoder Created an issue here: https://github.com/hackclub/contribute/issues/20

**Pull request merged**
