### PR TITLE
Format with Prettier

### PR DESCRIPTION
**Pull request by exu3**
This PR adds a Prettier configuration file (following the style of the existing code - semicolons, double quotes, etc).

I have "format on save" enabled, and I noticed that my own Prettier config kept formatting all the files in a different style, so this PR just adds a configuration scoped to this project to keep things consistent.

This is sort of opinionated, not sure if it's desired.

### CODE REVIEW

**Comment by jessicard** [comment]
Ooooh interesting! I'll let you and @sampoder decide if this makes sense, as you all have precedent on what we've done on other Hack Club repositories :)

**Comment by exu3** [comment]
This configuration file won't do anything if you don't use Prettier. I think some people just might not be clear on what this file does, but it shouldn't cause any issues or require additional setup.

**Comment by exu3** [comment]
Totally cool with closing this PR if it makes things more confusing!

**Review by sampoder — APPROVED** [review]
having a config is handy

**Pull request merged**
